### ISSUE TITLE
Selfhost SPMD: lower scalar foreach reference loops

### ISSUE THREAD

**Issue by JoNil-Botta** [JoNil-Botta/typelisp#1012]
Task

Add selfhost scalar lowering for `foreach`, producing the reference loop semantics required by `SPEC.md` section 5.15.

Findings

- `selfhost/compiler_parse_core.tl` and `selfhost/compiler_typecheck.tl` already accept simple `foreach` forms.
- `selfhost/compiler_lower.tl` currently has no `AstExprForeach` case in `lower-expr-with-type`, so parsed/typechecked programs fail at lowering with `lower: unsupported expression`.
- The Rust lowering path has the existing scalar reference behavior and integration fixtures under `tests/integration/spmd_foreach.tl`.
- This is the scalar correctness baseline needed before or alongside SIMD backend work.

Likely files/modules

- `selfhost/compiler_lower.tl`
- `selfhost/compiler_ir_types.tl` only if existing scalar branch/jump/phi instructions are insufficient
- `selfhost/compiler_lower_smoke.tl`
- `tests/tl_compiler_lower_compile.rs`
- `tests/integration/spmd_foreach.tl` as the behavioral oracle for a selfhost-runner fixture once available

Acceptance criteria

- `foreach` lowers to an ordinary scalar loop over the half-open range `[start, end)`.
- `start` and `end` are evaluated exactly once before the loop.
- If `end <= start`, the body is not evaluated.
- The loop index binding is available only inside the body and advances by one logical iteration.
- The lowered expression has type `unit` and preserves current dynamic-array bounds checks from `array-ref`/`array-set!`.
- Existing simple map/zip examples over `i32`, `i64`, and `f64` arrays lower successfully on the scalar path.
- Smoke tests cover zero-length, non-zero, and nested ordinary-expression cases; diagnostics still come from typecheck for non-unit bodies.

Assumptions/blockers

- This issue does not implement AVX2/AVX-512 vector lowering or backend-mode CLI support.
- It can be implemented before full uniform/varying enforcement, but should not accept behavior that conflicts with #1010 once that lands.

Links

- Decomposes #898.
- Implements part of the selfhost SPMD parity umbrella #791.
