### ISSUE TITLE
stdlib/crypto: mark SHA-256 operation Results must-use

### ISSUE THREAD

**Issue by JoNil** [JoNil-Botta/typelisp#7721]
Parent rollout: #7351
Handwritten stdlib decomposition: #7362
Migration tracker: #7350
Introduced by: #7710

## Task

Mark the handwritten SHA-256 operation-result aggregates introduced by #7710 as `(:must-use)`, then resolve every `unused-must-use-value` finding caused by them across the repository. Keep error payload, hashing state, and digest data unmarked.

This is the crypto-domain migration leaf missing from the pre-#7710 handwritten stdlib decomposition. It does not implement aggregate metadata, semantic discard collection, lint policy, or command/LSP adapters.

## Findings

Audit baseline: `main@436b029e`, 2026-09-12.

`stdlib/crypto_sha256.tl` now declares four handwritten recoverable operation Results, all of which require acknowledgement:

- `Sha256LengthResult`: internal checked message-length addition; discard loses the only overlength/overflow failure.
- `Sha256UpdateResult`: streaming state extension; discard loses finalized, invalid-state, invalid-source, and message-too-long failures even though success carries no payload.
- `Sha256FinalizeResult`: finalization/one-shot digest result; discard loses either the digest or the typed lifecycle/state/input failure.
- `Sha256FinalizeIntoResult`: checked raw-sink finalization; discard loses output validation and lifecycle/state failure, including from the consuming wipe-on-return adapter.

Current checked-in consumers in the module and `stdlib/tests/crypto_sha256_inline.tl` explicitly match these values. That does not make the declarations optional: downstream TLS, RSA, HMAC, and HKDF work will add consumers, and a discarded unit-success Result still hides failure.

Keep `Sha256Error` unmarked as an error payload, `Sha256State` unmarked as ordinary explicit streaming state, and `Sha256Digest` unmarked as ordinary public digest data. Marker eligibility must follow declaration intent, never `Result` spelling or enum shape.

The former handwritten stdlib audit #7362 predates #7710 and split six domain leaves whose 83 direct Result enums did not include crypto SHA-256. No open or closed issue mentions `Sha256UpdateResult`, and no existing migration leaf owns `stdlib/crypto_sha256.tl`; this is an independent seventh leaf rather than scope for randomness leaf #7630.

## Likely files/modules

- `stdlib/crypto_sha256.tl`
- `stdlib/tests/crypto_sha256_inline.tl` and unsafe-adapter rejection fixtures
- `stdlib/README.md` decision inventory
- all current and future compiler/stdlib/tool consumers reported by #7349, including TLS/RSA/HMAC/HKDF leaves

## Acceptance criteria

- Re-run the handwritten crypto declaration/return screen against current `main`; inventory all four operation Results and the three named error/state/data exclusions with returning APIs, marked decision, and rationale.
- Mark exactly the four operation-result enums once at their declarations. Keep `Sha256Error`, `Sha256State`, and `Sha256Digest` unmarked unless a separately documented contract change justifies otherwise.
- Run #7349 across root, stdlib, tools, packages, generated source, and native-TLCI consumers. Match/propagate each failure or acknowledge a deliberate discard with a descriptive underscore-prefixed binding; add no blanket allow, spelling exemption, or permanent baseline.
- Preserve update atomicity on rejected input, message-length bounds, finalization exactly-once behavior, state/digest wiping, raw pointer and output-length validation, digest bytes, evaluation order, ABI/layout, and original error identity.
- Tests cover discarded versus consumed `Sha256LengthResult`, `Sha256UpdateResult`, `Sha256FinalizeResult`, and `Sha256FinalizeIntoResult`; explicit deliberate acknowledgement; and representative unmarked error/state/digest controls. Include unit-success update/finalize-into paths so payload-free success does not weaken the warning.
- Source, qualified aliases, packages, checked-in generated source, and any native-TLCI surface preserve marker identity and ordered diagnostics.
- Report four marked declarations, three principal exclusions, findings by consumer subsystem, explicit acknowledgements, handled errors, behavior changes, and tests.
- Run `typelisp fmt`, focused SHA-256 tests under the checked-in memory cap, safety/shape gates, and hosted stdlib/bootstrap/Linux/Windows gates.

## Assumptions / blockers

Blocked on #7348 for ABI-neutral `(:must-use)` metadata and #7349 for semantic discard findings. Replace `blocked` with `ready-for-implementation` only after both close.

This issue owns handwritten SHA-256 declarations and every finding they cause. Generated crypto families, if added later, require an explicit owning leaf rather than being folded into this handwritten scope without triage.
